import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    'app.name': 'WhatsUP',
    'app.tagline': 'Discover events in your area',

    // Navigation
    'nav.back': 'Back',
    'nav.settings': 'Settings',
    'nav.close': 'Close',

    // Settings
    'settings.title': 'Settings',
    'settings.account': 'ACCOUNT',
    'settings.appSettings': 'APP SETTINGS',
    'settings.support': 'SUPPORT',
    'settings.version': 'APP VERSION',

    // Account
    'account.myProfile': 'My Profile',
    'account.savedEvents': 'Saved Events',
    'account.notifications': 'Notifications',
    'account.notLoggedIn': 'Not logged in',
    'account.loginToSave': 'Log in to save events',
    'account.logout': 'Log out',
    'account.logoutConfirm': 'Do you really want to log out?',

    // Authentication
    'auth.email': 'Email',
    'auth.sendCode': 'Send code to email',
    'auth.verifyCode': 'Verify code',
    'auth.codeSent': 'A 6-digit code has been sent to your email!',
    'auth.enterCode': 'Enter 6-digit code',
    'auth.youWillReceive': 'You will receive a 6-digit code via email',
    'auth.codeSentTo': 'Code sent to:',
    'auth.changeEmail': 'Change email',
    'auth.invalidEmail': 'Please enter a valid email address.',
    'auth.invalidCode': 'Invalid code. Please check your email and try again.',

    // Profile
    'profile.complete': 'Complete your profile',
    'profile.requiredFields': '* Required fields',
    'profile.fullName': 'Full Name',
    'profile.phoneNumber': 'Phone Number',
    'profile.dateOfBirth': 'Date of Birth',
    'profile.location': 'Location',
    'profile.createProfile': 'Create profile',
    'profile.save': 'Save',
    'profile.edit': 'Edit',
    'profile.cancel': 'Cancel',
    'profile.saving': 'Saving...',
    'profile.personalInfo': 'PERSONAL INFORMATION',
    'profile.accountInfo': 'ACCOUNT INFORMATION',
    'profile.accountCreated': 'Account created',
    'profile.lastLogin': 'Last login',
    'profile.emailVerified': 'Email verified',
    'profile.yes': 'Yes',
    'profile.no': 'No',
    'profile.notSpecified': 'Not specified',
    'profile.helpText': 'This information helps us personalize your experience',
    'profile.enterName': 'Please enter your name.',
    'profile.invalidPhone': 'Please enter a valid phone number.',
    'profile.ageTooYoung': 'You must be at least 13 years old.',
    'profile.invalidDate': 'Please enter a valid date of birth.',

    // Language
    'language.title': 'Language & Region',
    'language.selectLanguage': 'SELECT LANGUAGE',
    'language.english': 'English',
    'language.german': 'German (Deutsch)',
    'language.french': 'French (Français)',
    'language.spanish': 'Spanish (Español)',
    'language.currentLanguage': 'Current language',

    // Saved Events
    'savedEvents.title': 'Saved Events',
    'savedEvents.count': 'events saved',
    'savedEvents.count_one': 'event saved',
    'savedEvents.loading': 'Loading saved events...',
    'savedEvents.empty': 'No saved events',
    'savedEvents.emptyText': 'Save events to find them later!',
    'savedEvents.discover': 'Discover events',
    'savedEvents.note': 'Note',
    'savedEvents.viewTickets': 'View tickets',
    'savedEvents.savedOn': 'Saved',

    // Support
    'support.feedback': 'Send feedback',
    'support.help': 'Help & FAQ',
    'support.about': 'About WhatsUP',
    'support.contact': 'Contact',
    'support.comingSoon': 'will be available in a future version!',

    // App Settings
    'appSettings.languageRegion': 'Language & Region',
    'appSettings.appearance': 'Appearance',
    'appSettings.locationSettings': 'Location Settings',
    'appSettings.cacheData': 'Cache & Data',

    // Navigation Header
    'nav.findUniqueEvents': 'Find unique events!',
    'nav.list': 'List',
    'nav.map': 'Map',
    'nav.filter': 'Filter',
    'nav.new': 'New',
    'nav.searchHistory': 'Search History',
    'nav.activeSearch': 'ACTIVE SEARCH',
    'nav.previousSearches': 'PREVIOUS SEARCHES',
    'nav.savedTemplates': 'SAVED TEMPLATES',
    'nav.newSearch': 'New Search',
    'nav.deleteAll': 'Delete All',
    'nav.load': 'Load',
    'nav.apply': 'Apply',
    'nav.quickFilter': 'Quick Filter',
    'nav.activeFilters': 'filters active',
    'nav.reset': 'Reset',

    // Quick Filters
    'filter.when': 'WHEN?',
    'filter.howMuch': 'HOW MUCH?',
    'filter.howFar': 'HOW FAR?',
    'filter.special': 'SPECIAL',
    'filter.favorites': 'FAVORITES',
    'filter.now': 'Now',
    'filter.today': 'Today',
    'filter.tomorrow': 'Tomorrow',
    'filter.thisWeek': 'This Week',
    'filter.weekend': 'Weekend',
    'filter.free': '🆓 Free',
    'filter.under20': '< 20.-',
    'filter.under50': '< 50.-',
    'filter.any': 'Any',
    'filter.walking': 'Walking',
    'filter.under5km': '< 5km',
    'filter.under10km': '< 10km',
    'filter.indoor': '🏠 Indoor',
    'filter.accessible': '♿ Accessible',
    'filter.withKids': '👶 With Kids',
    'filter.tickets': '🎫 Tickets',
    'filter.showFavorites': '💖 Show favorites',
    'filter.noFavorites': 'No favorites available. Mark events with ❤️ to find them here.',
    'filter.favoritesCount': 'favorite(s) saved',

    // Event Card
    'event.free': 'Free',
    'event.tickets': 'Tickets',
    'event.website': 'Website',
    'event.details': 'Details',
    'event.oclock': 'o\'clock',

    // Search Results
    'search.noEvents': 'No Events Found 😔',
    'search.noEventsText': 'No matching events found for the selected filters.',
    'search.suggestions': '💡 Try:',
    'search.expandRadius': '• Expand the search radius',
    'search.otherCategories': '• Choose other categories',
    'search.changeTimeframe': '• Change the timeframe',
    'search.removeFilters': '• Remove special filters',
    'search.activateDemoMode': '🎯 Activate demo mode',
    'search.newSearch': '🔄 New Search',
    'search.events': 'Events',
    'search.resultsFound': 'results found',
    'search.agoHours': 'hours ago',
    'search.agoDays': 'days ago',
    'search.agoMinutes': 'few minutes ago',
    'search.agoHour': '1 hour ago',
    'search.agoDay': '1 day ago',

    // Start Screen
    'start.mode': '🎲 MODE',
    'start.standard': 'Standard',
    'start.discover': 'Discover',
    'start.location': '📍 LOCATION',
    'start.radius': '🎯 RADIUS',
    'start.categories': '📂 CATEGORIES',
    'start.timeframe': '📅 TIMEFRAME',
    'start.budget': '💰 BUDGET',
    'start.filters': '⚡ FILTERS',
    'start.enterLocation': 'Enter city or address...',
    'start.useCurrentLocation': 'Use current location',
    'start.chooseCategories': 'Choose categories',
    'start.categoriesSelected': 'categories',
    'start.chooseTimeframe': 'Choose time period',
    'start.chooseBudget': 'Choose budget',
    'start.chooseFilters': 'Choose filters',
    'start.filtersActive': 'filters active',
    'start.startSearch': '🔍 Start Event Search',
    'start.showResults': 'Show Previous Results',
    'start.discoverMode': 'Prioritizes unique & experimental events',
    'start.standardMode': 'Relevance-based search',
    'start.selectLocation': 'Please select location',
    'start.invalidDateRange': 'End date must be after start date',
    'start.km': 'km',
    'start.onlyFreeEvents': 'Only Free Events',
    'start.allDates': 'All Dates',
    'start.custom': 'Choose custom time period',
    'start.from': 'From:',
    'start.to': 'To:',
    'start.selectStartDate': 'Select start date',
    'start.selectEndDate': 'Select end date',
    'start.next7Days': 'Next 7 Days',
    'start.nextMonth': 'Next Month',
    'start.requestCategory': 'Request New Category',
    'start.requestFilter': 'Request New Filter',
  },

  de: {
    // App
    'app.name': 'WhatsUP',
    'app.tagline': 'Entdecke Events in deiner Nähe',

    // Navigation
    'nav.back': 'Zurück',
    'nav.settings': 'Einstellungen',
    'nav.close': 'Schließen',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.account': 'ACCOUNT',
    'settings.appSettings': 'APP-EINSTELLUNGEN',
    'settings.support': 'SUPPORT',
    'settings.version': 'APP VERSION',

    // Account
    'account.myProfile': 'Mein Profil',
    'account.savedEvents': 'Gespeicherte Events',
    'account.notifications': 'Benachrichtigungen',
    'account.notLoggedIn': 'Nicht angemeldet',
    'account.loginToSave': 'Melden Sie sich an, um Events zu speichern',
    'account.logout': 'Ausloggen',
    'account.logoutConfirm': 'Möchten Sie sich wirklich ausloggen?',

    // Authentication
    'auth.email': 'E-Mail',
    'auth.sendCode': 'Code an E-Mail senden',
    'auth.verifyCode': 'Code bestätigen',
    'auth.codeSent': 'Ein 6-stelliger Code wurde an Ihre E-Mail gesendet!',
    'auth.enterCode': '6-stelligen Code eingeben',
    'auth.youWillReceive': 'Sie erhalten einen 6-stelligen Code per E-Mail',
    'auth.codeSentTo': 'Code gesendet an:',
    'auth.changeEmail': 'E-Mail ändern',
    'auth.invalidEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    'auth.invalidCode': 'Ungültiger Code. Bitte überprüfen Sie Ihre E-Mail und versuchen Sie es erneut.',

    // Profile
    'profile.complete': 'Vervollständigen Sie Ihr Profil',
    'profile.requiredFields': '* Pflichtfelder',
    'profile.fullName': 'Vollständiger Name',
    'profile.phoneNumber': 'Telefonnummer',
    'profile.dateOfBirth': 'Geburtsdatum',
    'profile.location': 'Standort',
    'profile.createProfile': 'Profil erstellen',
    'profile.save': 'Speichern',
    'profile.edit': 'Bearbeiten',
    'profile.cancel': 'Abbrechen',
    'profile.saving': 'Wird gespeichert...',
    'profile.personalInfo': 'PERSÖNLICHE INFORMATIONEN',
    'profile.accountInfo': 'KONTO-INFORMATIONEN',
    'profile.accountCreated': 'Konto erstellt',
    'profile.lastLogin': 'Letzte Anmeldung',
    'profile.emailVerified': 'E-Mail verifiziert',
    'profile.yes': 'Ja',
    'profile.no': 'Nein',
    'profile.notSpecified': 'Nicht angegeben',
    'profile.helpText': 'Diese Informationen helfen uns, Ihre Erfahrung zu personalisieren',
    'profile.enterName': 'Bitte geben Sie Ihren Namen ein.',
    'profile.invalidPhone': 'Bitte geben Sie eine gültige Telefonnummer ein.',
    'profile.ageTooYoung': 'Sie müssen mindestens 13 Jahre alt sein.',
    'profile.invalidDate': 'Bitte geben Sie ein gültiges Geburtsdatum ein.',

    // Language
    'language.title': 'Sprache & Region',
    'language.selectLanguage': 'SPRACHE WÄHLEN',
    'language.english': 'Englisch (English)',
    'language.german': 'Deutsch',
    'language.french': 'Französisch (Français)',
    'language.spanish': 'Spanisch (Español)',
    'language.currentLanguage': 'Aktuelle Sprache',

    // Saved Events
    'savedEvents.title': 'Gespeicherte Events',
    'savedEvents.count': 'Events gespeichert',
    'savedEvents.count_one': 'Event gespeichert',
    'savedEvents.loading': 'Lade gespeicherte Events...',
    'savedEvents.empty': 'Keine gespeicherten Events',
    'savedEvents.emptyText': 'Speichern Sie Events, um sie später wiederzufinden!',
    'savedEvents.discover': 'Events entdecken',
    'savedEvents.note': 'Notiz',
    'savedEvents.viewTickets': 'Tickets ansehen',
    'savedEvents.savedOn': 'Gespeichert',

    // Support
    'support.feedback': 'Feedback senden',
    'support.help': 'Hilfe & FAQ',
    'support.about': 'Über WhatsUP',
    'support.contact': 'Kontakt',
    'support.comingSoon': 'wird in einer zukünftigen Version verfügbar sein!',

    // App Settings
    'appSettings.languageRegion': 'Sprache & Region',
    'appSettings.appearance': 'Darstellung',
    'appSettings.locationSettings': 'Standort-Einstellungen',
    'appSettings.cacheData': 'Cache & Daten',

    // Navigation Header
    'nav.findUniqueEvents': 'Find unique events!',
    'nav.list': 'Liste',
    'nav.map': 'Karte',
    'nav.filter': 'Filter',
    'nav.new': 'Neu',
    'nav.searchHistory': 'Suchverlauf',
    'nav.activeSearch': 'AKTIVE SUCHE',
    'nav.previousSearches': 'LETZTE SUCHEN',
    'nav.savedTemplates': 'GESPEICHERTE VORLAGEN',
    'nav.newSearch': 'Neue Suche',
    'nav.deleteAll': 'Alle löschen',
    'nav.load': 'Laden',
    'nav.apply': 'Anwenden',
    'nav.quickFilter': 'Schnellfilter',
    'nav.activeFilters': 'Filter aktiv',
    'nav.reset': 'Zurücksetzen',

    // Quick Filters
    'filter.when': 'WANN?',
    'filter.howMuch': 'WIE TEUER?',
    'filter.howFar': 'WIE WEIT?',
    'filter.special': 'SPEZIAL',
    'filter.favorites': 'FAVORITEN',
    'filter.now': 'Jetzt',
    'filter.today': 'Heute',
    'filter.tomorrow': 'Morgen',
    'filter.thisWeek': 'Diese Woche',
    'filter.weekend': 'Wochenende',
    'filter.free': '🆓 Gratis',
    'filter.under20': '< 20.-',
    'filter.under50': '< 50.-',
    'filter.any': 'Egal',
    'filter.walking': 'Zu Fuss',
    'filter.under5km': '< 5km',
    'filter.under10km': '< 10km',
    'filter.indoor': '🏠 Indoor',
    'filter.accessible': '♿ Barrierefrei',
    'filter.withKids': '👶 Mit Kindern',
    'filter.tickets': '🎫 Tickets',
    'filter.showFavorites': '💖 Favoriten anzeigen',
    'filter.noFavorites': 'Keine Favoriten vorhanden. Markiere Events mit ❤️ um sie hier zu finden.',
    'filter.favoritesCount': 'Favorit(en) gespeichert',

    // Event Card
    'event.free': 'Gratis',
    'event.tickets': 'Tickets',
    'event.website': 'Website',
    'event.details': 'Details',
    'event.oclock': 'Uhr',

    // Search Results
    'search.noEvents': 'Keine Events gefunden 😔',
    'search.noEventsText': 'Für die gewählten Filter wurden keine passenden Events gefunden.',
    'search.suggestions': '💡 Versuchen Sie:',
    'search.expandRadius': '• Erweitern Sie den Suchradius',
    'search.otherCategories': '• Wählen Sie andere Kategorien',
    'search.changeTimeframe': '• Ändern Sie den Zeitraum',
    'search.removeFilters': '• Entfernen Sie spezielle Filter',
    'search.activateDemoMode': '🎯 Demo-Modus aktivieren',
    'search.newSearch': '🔄 Neue Suche',
    'search.events': 'Events',
    'search.resultsFound': 'Ergebnisse gefunden',
    'search.agoHours': 'Std',
    'search.agoDays': 'Tagen',
    'search.agoMinutes': 'vor wenigen Minuten',
    'search.agoHour': 'vor 1 Std',
    'search.agoDay': 'vor 1 Tag',

    // Start Screen
    'start.mode': '🎲 MODUS',
    'start.standard': 'Standard',
    'start.discover': 'Entdecken',
    'start.location': '📍 STANDORT',
    'start.radius': '🎯 RADIUS',
    'start.categories': '📂 KATEGORIEN',
    'start.timeframe': '📅 ZEITRAUM',
    'start.budget': '💰 BUDGET',
    'start.filters': '⚡ FILTER',
    'start.enterLocation': 'Stadt oder Adresse eingeben...',
    'start.useCurrentLocation': 'Aktuellen Standort verwenden',
    'start.chooseCategories': 'Kategorien wählen',
    'start.categoriesSelected': 'Kategorien',
    'start.chooseTimeframe': 'Zeitraum wählen',
    'start.chooseBudget': 'Budget wählen',
    'start.chooseFilters': 'Filter wählen',
    'start.filtersActive': 'Filter aktiv',
    'start.startSearch': '🔍 Event-Suche starten',
    'start.showResults': 'Bisherige Ergebnisse anzeigen',
    'start.discoverMode': 'Priorisiert einzigartige & experimentelle Events',
    'start.standardMode': 'Relevanz-basierte Suche',
    'start.selectLocation': 'Bitte Standort wählen',
    'start.invalidDateRange': 'Enddatum muss nach Startdatum liegen',
    'start.km': 'km',
    'start.onlyFreeEvents': 'Nur Gratis-Events',
    'start.allDates': 'An allen Terminen',
    'start.custom': 'Eigenen Zeitraum wählen',
    'start.from': 'Von:',
    'start.to': 'Bis:',
    'start.selectStartDate': 'Startdatum wählen',
    'start.selectEndDate': 'Enddatum wählen',
    'start.next7Days': 'Nächste 7 Tage',
    'start.nextMonth': 'Nächsten Monat',
    'start.requestCategory': 'Neue Kategorie beantragen',
    'start.requestFilter': 'Neuen Filter beantragen',
  },

  fr: {
    // App
    'app.name': 'WhatsUP',
    'app.tagline': 'Découvrez des événements près de chez vous',

    // Navigation
    'nav.back': 'Retour',
    'nav.settings': 'Paramètres',
    'nav.close': 'Fermer',

    // Settings
    'settings.title': 'Paramètres',
    'settings.account': 'COMPTE',
    'settings.appSettings': 'PARAMÈTRES DE L\'APPLICATION',
    'settings.support': 'SUPPORT',
    'settings.version': 'VERSION DE L\'APPLICATION',

    // Account
    'account.myProfile': 'Mon profil',
    'account.savedEvents': 'Événements sauvegardés',
    'account.notifications': 'Notifications',
    'account.notLoggedIn': 'Non connecté',
    'account.loginToSave': 'Connectez-vous pour sauvegarder des événements',
    'account.logout': 'Se déconnecter',
    'account.logoutConfirm': 'Voulez-vous vraiment vous déconnecter?',

    // Authentication
    'auth.email': 'E-mail',
    'auth.sendCode': 'Envoyer le code par e-mail',
    'auth.verifyCode': 'Vérifier le code',
    'auth.codeSent': 'Un code à 6 chiffres a été envoyé à votre e-mail!',
    'auth.enterCode': 'Entrez le code à 6 chiffres',
    'auth.youWillReceive': 'Vous recevrez un code à 6 chiffres par e-mail',
    'auth.codeSentTo': 'Code envoyé à:',
    'auth.changeEmail': 'Changer l\'e-mail',
    'auth.invalidEmail': 'Veuillez entrer une adresse e-mail valide.',
    'auth.invalidCode': 'Code invalide. Veuillez vérifier votre e-mail et réessayer.',

    // Profile
    'profile.complete': 'Complétez votre profil',
    'profile.requiredFields': '* Champs obligatoires',
    'profile.fullName': 'Nom complet',
    'profile.phoneNumber': 'Numéro de téléphone',
    'profile.dateOfBirth': 'Date de naissance',
    'profile.location': 'Lieu',
    'profile.createProfile': 'Créer le profil',
    'profile.save': 'Enregistrer',
    'profile.edit': 'Modifier',
    'profile.cancel': 'Annuler',
    'profile.saving': 'Enregistrement...',
    'profile.personalInfo': 'INFORMATIONS PERSONNELLES',
    'profile.accountInfo': 'INFORMATIONS DU COMPTE',
    'profile.accountCreated': 'Compte créé',
    'profile.lastLogin': 'Dernière connexion',
    'profile.emailVerified': 'E-mail vérifié',
    'profile.yes': 'Oui',
    'profile.no': 'Non',
    'profile.notSpecified': 'Non spécifié',
    'profile.helpText': 'Ces informations nous aident à personnaliser votre expérience',
    'profile.enterName': 'Veuillez entrer votre nom.',
    'profile.invalidPhone': 'Veuillez entrer un numéro de téléphone valide.',
    'profile.ageTooYoung': 'Vous devez avoir au moins 13 ans.',
    'profile.invalidDate': 'Veuillez entrer une date de naissance valide.',

    // Language
    'language.title': 'Langue et région',
    'language.selectLanguage': 'SÉLECTIONNER LA LANGUE',
    'language.english': 'Anglais (English)',
    'language.german': 'Allemand (Deutsch)',
    'language.french': 'Français',
    'language.spanish': 'Espagnol (Español)',
    'language.currentLanguage': 'Langue actuelle',

    // Saved Events
    'savedEvents.title': 'Événements sauvegardés',
    'savedEvents.count': 'événements sauvegardés',
    'savedEvents.count_one': 'événement sauvegardé',
    'savedEvents.loading': 'Chargement des événements sauvegardés...',
    'savedEvents.empty': 'Aucun événement sauvegardé',
    'savedEvents.emptyText': 'Sauvegardez des événements pour les retrouver plus tard!',
    'savedEvents.discover': 'Découvrir des événements',
    'savedEvents.note': 'Note',
    'savedEvents.viewTickets': 'Voir les billets',
    'savedEvents.savedOn': 'Sauvegardé',

    // Support
    'support.feedback': 'Envoyer un commentaire',
    'support.help': 'Aide et FAQ',
    'support.about': 'À propos de WhatsUP',
    'support.contact': 'Contact',
    'support.comingSoon': 'sera disponible dans une future version!',

    // App Settings
    'appSettings.languageRegion': 'Langue et région',
    'appSettings.appearance': 'Apparence',
    'appSettings.locationSettings': 'Paramètres de localisation',
    'appSettings.cacheData': 'Cache et données',

    // Navigation Header
    'nav.findUniqueEvents': 'Trouvez des événements uniques!',
    'nav.list': 'Liste',
    'nav.map': 'Carte',
    'nav.filter': 'Filtre',
    'nav.new': 'Nouveau',
    'nav.searchHistory': 'Historique de recherche',
    'nav.activeSearch': 'RECHERCHE ACTIVE',
    'nav.previousSearches': 'RECHERCHES PRÉCÉDENTES',
    'nav.savedTemplates': 'MODÈLES ENREGISTRÉS',
    'nav.newSearch': 'Nouvelle recherche',
    'nav.deleteAll': 'Tout supprimer',
    'nav.load': 'Charger',
    'nav.apply': 'Appliquer',
    'nav.quickFilter': 'Filtre rapide',
    'nav.activeFilters': 'filtres actifs',
    'nav.reset': 'Réinitialiser',

    // Quick Filters
    'filter.when': 'QUAND?',
    'filter.howMuch': 'COMBIEN?',
    'filter.howFar': 'QUELLE DISTANCE?',
    'filter.special': 'SPÉCIAL',
    'filter.favorites': 'FAVORIS',
    'filter.now': 'Maintenant',
    'filter.today': 'Aujourd\'hui',
    'filter.tomorrow': 'Demain',
    'filter.thisWeek': 'Cette semaine',
    'filter.weekend': 'Week-end',
    'filter.free': '🆓 Gratuit',
    'filter.under20': '< 20.-',
    'filter.under50': '< 50.-',
    'filter.any': 'Peu importe',
    'filter.walking': 'À pied',
    'filter.under5km': '< 5km',
    'filter.under10km': '< 10km',
    'filter.indoor': '🏠 Intérieur',
    'filter.accessible': '♿ Accessible',
    'filter.withKids': '👶 Avec enfants',
    'filter.tickets': '🎫 Billets',
    'filter.showFavorites': '💖 Afficher les favoris',
    'filter.noFavorites': 'Aucun favori disponible. Marquez des événements avec ❤️ pour les trouver ici.',
    'filter.favoritesCount': 'favori(s) enregistré(s)',

    // Event Card
    'event.free': 'Gratuit',
    'event.tickets': 'Billets',
    'event.website': 'Site web',
    'event.details': 'Détails',
    'event.oclock': 'heures',

    // Search Results
    'search.noEvents': 'Aucun événement trouvé 😔',
    'search.noEventsText': 'Aucun événement correspondant trouvé pour les filtres sélectionnés.',
    'search.suggestions': '💡 Essayez:',
    'search.expandRadius': '• Élargir le rayon de recherche',
    'search.otherCategories': '• Choisir d\'autres catégories',
    'search.changeTimeframe': '• Modifier la période',
    'search.removeFilters': '• Supprimer les filtres spéciaux',
    'search.activateDemoMode': '🎯 Activer le mode démo',
    'search.newSearch': '🔄 Nouvelle recherche',
    'search.events': 'Événements',
    'search.resultsFound': 'résultats trouvés',
    'search.agoHours': 'heures',
    'search.agoDays': 'jours',
    'search.agoMinutes': 'il y a quelques minutes',
    'search.agoHour': 'il y a 1 heure',
    'search.agoDay': 'il y a 1 jour',

    // Start Screen
    'start.mode': '🎲 MODE',
    'start.standard': 'Standard',
    'start.discover': 'Découvrir',
    'start.location': '📍 LIEU',
    'start.radius': '🎯 RAYON',
    'start.categories': '📂 CATÉGORIES',
    'start.timeframe': '📅 PÉRIODE',
    'start.budget': '💰 BUDGET',
    'start.filters': '⚡ FILTRES',
    'start.enterLocation': 'Entrez une ville ou une adresse...',
    'start.useCurrentLocation': 'Utiliser la position actuelle',
    'start.chooseCategories': 'Choisir les catégories',
    'start.categoriesSelected': 'catégories',
    'start.chooseTimeframe': 'Choisir la période',
    'start.chooseBudget': 'Choisir le budget',
    'start.chooseFilters': 'Choisir les filtres',
    'start.filtersActive': 'filtres actifs',
    'start.startSearch': '🔍 Démarrer la recherche d\'événements',
    'start.showResults': 'Afficher les résultats précédents',
    'start.discoverMode': 'Priorise les événements uniques et expérimentaux',
    'start.standardMode': 'Recherche basée sur la pertinence',
    'start.selectLocation': 'Veuillez sélectionner un lieu',
    'start.invalidDateRange': 'La date de fin doit être après la date de début',
    'start.km': 'km',
    'start.onlyFreeEvents': 'Seulement les événements gratuits',
    'start.allDates': 'Toutes les dates',
    'start.custom': 'Choisir une période personnalisée',
    'start.from': 'De:',
    'start.to': 'À:',
    'start.selectStartDate': 'Sélectionner la date de début',
    'start.selectEndDate': 'Sélectionner la date de fin',
    'start.next7Days': 'Les 7 prochains jours',
    'start.nextMonth': 'Le mois prochain',
    'start.requestCategory': 'Demander une nouvelle catégorie',
    'start.requestFilter': 'Demander un nouveau filtre',
  },

  es: {
    // App
    'app.name': 'WhatsUP',
    'app.tagline': 'Descubre eventos en tu área',

    // Navigation
    'nav.back': 'Atrás',
    'nav.settings': 'Configuración',
    'nav.close': 'Cerrar',

    // Settings
    'settings.title': 'Configuración',
    'settings.account': 'CUENTA',
    'settings.appSettings': 'CONFIGURACIÓN DE LA APLICACIÓN',
    'settings.support': 'SOPORTE',
    'settings.version': 'VERSIÓN DE LA APLICACIÓN',

    // Account
    'account.myProfile': 'Mi perfil',
    'account.savedEvents': 'Eventos guardados',
    'account.notifications': 'Notificaciones',
    'account.notLoggedIn': 'No conectado',
    'account.loginToSave': 'Inicia sesión para guardar eventos',
    'account.logout': 'Cerrar sesión',
    'account.logoutConfirm': '¿Realmente quieres cerrar sesión?',

    // Authentication
    'auth.email': 'Correo electrónico',
    'auth.sendCode': 'Enviar código por correo',
    'auth.verifyCode': 'Verificar código',
    'auth.codeSent': '¡Se ha enviado un código de 6 dígitos a tu correo!',
    'auth.enterCode': 'Ingresa el código de 6 dígitos',
    'auth.youWillReceive': 'Recibirás un código de 6 dígitos por correo electrónico',
    'auth.codeSentTo': 'Código enviado a:',
    'auth.changeEmail': 'Cambiar correo',
    'auth.invalidEmail': 'Por favor ingresa una dirección de correo válida.',
    'auth.invalidCode': 'Código inválido. Por favor verifica tu correo e intenta de nuevo.',

    // Profile
    'profile.complete': 'Completa tu perfil',
    'profile.requiredFields': '* Campos obligatorios',
    'profile.fullName': 'Nombre completo',
    'profile.phoneNumber': 'Número de teléfono',
    'profile.dateOfBirth': 'Fecha de nacimiento',
    'profile.location': 'Ubicación',
    'profile.createProfile': 'Crear perfil',
    'profile.save': 'Guardar',
    'profile.edit': 'Editar',
    'profile.cancel': 'Cancelar',
    'profile.saving': 'Guardando...',
    'profile.personalInfo': 'INFORMACIÓN PERSONAL',
    'profile.accountInfo': 'INFORMACIÓN DE LA CUENTA',
    'profile.accountCreated': 'Cuenta creada',
    'profile.lastLogin': 'Último inicio de sesión',
    'profile.emailVerified': 'Correo verificado',
    'profile.yes': 'Sí',
    'profile.no': 'No',
    'profile.notSpecified': 'No especificado',
    'profile.helpText': 'Esta información nos ayuda a personalizar tu experiencia',
    'profile.enterName': 'Por favor ingresa tu nombre.',
    'profile.invalidPhone': 'Por favor ingresa un número de teléfono válido.',
    'profile.ageTooYoung': 'Debes tener al menos 13 años.',
    'profile.invalidDate': 'Por favor ingresa una fecha de nacimiento válida.',

    // Language
    'language.title': 'Idioma y región',
    'language.selectLanguage': 'SELECCIONAR IDIOMA',
    'language.english': 'Inglés (English)',
    'language.german': 'Alemán (Deutsch)',
    'language.french': 'Francés (Français)',
    'language.spanish': 'Español',
    'language.currentLanguage': 'Idioma actual',

    // Saved Events
    'savedEvents.title': 'Eventos guardados',
    'savedEvents.count': 'eventos guardados',
    'savedEvents.count_one': 'evento guardado',
    'savedEvents.loading': 'Cargando eventos guardados...',
    'savedEvents.empty': 'No hay eventos guardados',
    'savedEvents.emptyText': '¡Guarda eventos para encontrarlos después!',
    'savedEvents.discover': 'Descubrir eventos',
    'savedEvents.note': 'Nota',
    'savedEvents.viewTickets': 'Ver entradas',
    'savedEvents.savedOn': 'Guardado',

    // Support
    'support.feedback': 'Enviar comentarios',
    'support.help': 'Ayuda y preguntas frecuentes',
    'support.about': 'Acerca de WhatsUP',
    'support.contact': 'Contacto',
    'support.comingSoon': '¡estará disponible en una versión futura!',

    // App Settings
    'appSettings.languageRegion': 'Idioma y región',
    'appSettings.appearance': 'Apariencia',
    'appSettings.locationSettings': 'Configuración de ubicación',
    'appSettings.cacheData': 'Caché y datos',

    // Navigation Header
    'nav.findUniqueEvents': '¡Encuentra eventos únicos!',
    'nav.list': 'Lista',
    'nav.map': 'Mapa',
    'nav.filter': 'Filtro',
    'nav.new': 'Nuevo',
    'nav.searchHistory': 'Historial de búsqueda',
    'nav.activeSearch': 'BÚSQUEDA ACTIVA',
    'nav.previousSearches': 'BÚSQUEDAS ANTERIORES',
    'nav.savedTemplates': 'PLANTILLAS GUARDADAS',
    'nav.newSearch': 'Nueva búsqueda',
    'nav.deleteAll': 'Eliminar todo',
    'nav.load': 'Cargar',
    'nav.apply': 'Aplicar',
    'nav.quickFilter': 'Filtro rápido',
    'nav.activeFilters': 'filtros activos',
    'nav.reset': 'Restablecer',

    // Quick Filters
    'filter.when': '¿CUÁNDO?',
    'filter.howMuch': '¿CUÁNTO?',
    'filter.howFar': '¿QUÉ TAN LEJOS?',
    'filter.special': 'ESPECIAL',
    'filter.favorites': 'FAVORITOS',
    'filter.now': 'Ahora',
    'filter.today': 'Hoy',
    'filter.tomorrow': 'Mañana',
    'filter.thisWeek': 'Esta semana',
    'filter.weekend': 'Fin de semana',
    'filter.free': '🆓 Gratis',
    'filter.under20': '< 20.-',
    'filter.under50': '< 50.-',
    'filter.any': 'Cualquiera',
    'filter.walking': 'A pie',
    'filter.under5km': '< 5km',
    'filter.under10km': '< 10km',
    'filter.indoor': '🏠 Interior',
    'filter.accessible': '♿ Accesible',
    'filter.withKids': '👶 Con niños',
    'filter.tickets': '🎫 Entradas',
    'filter.showFavorites': '💖 Mostrar favoritos',
    'filter.noFavorites': 'No hay favoritos disponibles. Marca eventos con ❤️ para encontrarlos aquí.',
    'filter.favoritesCount': 'favorito(s) guardado(s)',

    // Event Card
    'event.free': 'Gratis',
    'event.tickets': 'Entradas',
    'event.website': 'Sitio web',
    'event.details': 'Detalles',
    'event.oclock': 'horas',

    // Search Results
    'search.noEvents': 'No se encontraron eventos 😔',
    'search.noEventsText': 'No se encontraron eventos que coincidan con los filtros seleccionados.',
    'search.suggestions': '💡 Intenta:',
    'search.expandRadius': '• Ampliar el radio de búsqueda',
    'search.otherCategories': '• Elegir otras categorías',
    'search.changeTimeframe': '• Cambiar el período de tiempo',
    'search.removeFilters': '• Eliminar filtros especiales',
    'search.activateDemoMode': '🎯 Activar modo demo',
    'search.newSearch': '🔄 Nueva búsqueda',
    'search.events': 'Eventos',
    'search.resultsFound': 'resultados encontrados',
    'search.agoHours': 'horas',
    'search.agoDays': 'días',
    'search.agoMinutes': 'hace unos minutos',
    'search.agoHour': 'hace 1 hora',
    'search.agoDay': 'hace 1 día',

    // Start Screen
    'start.mode': '🎲 MODO',
    'start.standard': 'Estándar',
    'start.discover': 'Descubrir',
    'start.location': '📍 UBICACIÓN',
    'start.radius': '🎯 RADIO',
    'start.categories': '📂 CATEGORÍAS',
    'start.timeframe': '📅 PERÍODO',
    'start.budget': '💰 PRESUPUESTO',
    'start.filters': '⚡ FILTROS',
    'start.enterLocation': 'Ingresa ciudad o dirección...',
    'start.useCurrentLocation': 'Usar ubicación actual',
    'start.chooseCategories': 'Elegir categorías',
    'start.categoriesSelected': 'categorías',
    'start.chooseTimeframe': 'Elegir período',
    'start.chooseBudget': 'Elegir presupuesto',
    'start.chooseFilters': 'Elegir filtros',
    'start.filtersActive': 'filtros activos',
    'start.startSearch': '🔍 Iniciar búsqueda de eventos',
    'start.showResults': 'Mostrar resultados anteriores',
    'start.discoverMode': 'Prioriza eventos únicos y experimentales',
    'start.standardMode': 'Búsqueda basada en relevancia',
    'start.selectLocation': 'Por favor selecciona una ubicación',
    'start.invalidDateRange': 'La fecha de fin debe ser posterior a la fecha de inicio',
    'start.km': 'km',
    'start.onlyFreeEvents': 'Solo eventos gratuitos',
    'start.allDates': 'Todas las fechas',
    'start.custom': 'Elegir período personalizado',
    'start.from': 'Desde:',
    'start.to': 'Hasta:',
    'start.selectStartDate': 'Seleccionar fecha de inicio',
    'start.selectEndDate': 'Seleccionar fecha de fin',
    'start.next7Days': 'Próximos 7 días',
    'start.nextMonth': 'Próximo mes',
    'start.requestCategory': 'Solicitar nueva categoría',
    'start.requestFilter': 'Solicitar nuevo filtro',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load from localStorage or default to German
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'de';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
